augment_epoch: 10
backbone: RN50
load_cache: true
load_pre_feat: true
search_hp: true
train_epoch: 20
dataset: caltech101
init_alpha: 3
init_beta: 1
init_eta: 0.1
init_gamma: 0.01
search_scale: [12, 5]
search_step: [200, 20]