augment_epoch: 10
backbone: RN50
load_cache: true
load_pre_feat: true
search_hp: true
train_epoch: 100
dataset: eurosat
init_alpha: 2
init_beta: 1
init_eta: 1.0
init_gamma: 1.0
search_scale: [12, 10]
search_step: [200, 20]