augment_epoch: 10
backbone: RN50
load_cache: true
load_pre_feat: true
search_hp: true
train_epoch: 20
dataset: sun397
init_alpha: 1.17
init_beta: 1
init_eta: 0.01
init_gamma: 0.001
search_scale: [12, 10]
search_step: [200, 20]